In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
import pickle

In [9]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head

<bound method NDFrame.head of       RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]>

In [10]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(["RowNumber","CustomerId","Surname"], axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [11]:
## Encode categorical variables - we are considering gender and country
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [12]:
## One Hot Encoding - geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
## Combine one hot encoded columns with the original data
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df])
data.head

<bound method NDFrame.head of       CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0           619.0     0.0  ...                NaN              NaN
1           608.0     0.0  ...                NaN              NaN
2           502.0     0.0  ...                NaN              NaN
3           699.0     0.0  ...                NaN              NaN
4           850.0     0.0  ...                NaN              NaN
...           ...     ...  ...                ...              ...
9995          NaN     NaN  ...                0.0              0.0
9996          NaN     NaN  ...                0.0              0.0
9997          NaN     NaN  ...                0.0              0.0
9998          NaN     NaN  ...                1.0              0.0
9999          NaN     NaN  ...                0.0              0.0

[20000 rows x 13 columns]>

In [21]:
## Save the encoders and scaler
with open('Label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [16]:
data.head

<bound method NDFrame.head of       CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0           619.0     0.0  ...                NaN              NaN
1           608.0     0.0  ...                NaN              NaN
2           502.0     0.0  ...                NaN              NaN
3           699.0     0.0  ...                NaN              NaN
4           850.0     0.0  ...                NaN              NaN
...           ...     ...  ...                ...              ...
9995          NaN     NaN  ...                0.0              0.0
9996          NaN     NaN  ...                0.0              0.0
9997          NaN     NaN  ...                0.0              0.0
9998          NaN     NaN  ...                1.0              0.0
9999          NaN     NaN  ...                0.0              0.0

[20000 rows x 13 columns]>

In [17]:
## Divide the dataset into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

## Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
X_train

array([[-0.70157205,  0.90488898,  0.00509723, ...,         nan,
                nan,         nan],
       [ 0.25470059,  0.90488898,  2.57743383, ...,         nan,
                nan,         nan],
       [-0.80551473,  0.90488898,  1.24362967, ...,         nan,
                nan,         nan],
       ...,
       [ 0.87835666, -1.10510794, -0.09017449, ...,         nan,
                nan,         nan],
       [ 0.17154644,  0.90488898,  0.38618414, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,  0.99167946,
        -0.5804702 , -0.5677979 ]])

In [27]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### Now will train ANN

### In basic ANN we have 1 input layer, few hidden layers and one output layer

### Then we perform forward propogation and backward propogation

### In Tensorflow we call ANN as sequential model
### When we start creating our ANN model

### 1. We need to initialize our sequential network
### 2. Then we need to create a hidden neuron, so we need to use 'Dense' library from keras
### 3. Activation function to be applied to every node -> Sigmoid, tab h ,Relu, Leaky Relu etc any can be applied
### 4. Optimizer - useful in back propogation - responsible in updating the weights
### 5. Loss function, try to reduce this
### 6. Metrics - usually in classification problem metrics is 'accuracy', in regression problem it is like mse, or mean absolute error etc
### 7. Training information - store logs in a folder and we use tensorboard which will display these logs in a vizualization graphs so easy to understand

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [21]:
(X_train.shape[1],)

(12,)

In [22]:
## Lets build our ANN model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## 1st hidden layer and connected with input layer
    Dense(32,activation='relu'), ## Hidden layer 2
    Dense(1,activation='sigmoid') ## output layer
])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [50]:
## optimizers
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [51]:
## Now our ANN model is ready as we saw above
## In order to apply fwd and backward propogation we need to compile this model
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [58]:
## Set up the tensorboard
import datetime
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir,histogram_freq=1)

In [59]:
## Setup Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [60]:
## Now, Time to Train the Model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test), epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
500/500 [==============================] - 0s 675us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 2/100
500/500 [==============================] - 0s 654us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 3/100
500/500 [==============================] - 0s 588us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 4/100
500/500 [==============================] - 0s 693us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 5/100
500/500 [==============================] - 0s 617us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 6/100
500/500 [==============================] - 0s 614us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 7/100
500/500 [==============================] - 0s 605us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 8/100
500/500 [==============================] - 0s 601us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 9/100
500/500 [==============================] - 0s 586us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 10/100
500/500 [==============================] - 0s 590us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045

In [61]:
model.save('model.h5')

/Users/harshveersinghnirwan/Downloads/annclassification_myproject/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [65]:
## Lets load tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [64]:
## to kill and restart the tensorboard
!kill 80821

In [66]:
%tensorboard --logdir logs/fit