In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
import pickle

In [9]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head

<bound method NDFrame.head of       RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]>

In [10]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(["RowNumber","CustomerId","Surname"], axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [11]:
## Encode categorical variables - we are considering gender and country
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [12]:
## One Hot Encoding - geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
## Combine one hot encoded columns with the original data
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df])
data.head

<bound method NDFrame.head of       CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0           619.0     0.0  ...                NaN              NaN
1           608.0     0.0  ...                NaN              NaN
2           502.0     0.0  ...                NaN              NaN
3           699.0     0.0  ...                NaN              NaN
4           850.0     0.0  ...                NaN              NaN
...           ...     ...  ...                ...              ...
9995          NaN     NaN  ...                0.0              0.0
9996          NaN     NaN  ...                0.0              0.0
9997          NaN     NaN  ...                0.0              0.0
9998          NaN     NaN  ...                1.0              0.0
9999          NaN     NaN  ...                0.0              0.0

[20000 rows x 13 columns]>

In [21]:
## Save the encoders and scaler
with open('Label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [16]:
data.head

<bound method NDFrame.head of       CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0           619.0     0.0  ...                NaN              NaN
1           608.0     0.0  ...                NaN              NaN
2           502.0     0.0  ...                NaN              NaN
3           699.0     0.0  ...                NaN              NaN
4           850.0     0.0  ...                NaN              NaN
...           ...     ...  ...                ...              ...
9995          NaN     NaN  ...                0.0              0.0
9996          NaN     NaN  ...                0.0              0.0
9997          NaN     NaN  ...                0.0              0.0
9998          NaN     NaN  ...                1.0              0.0
9999          NaN     NaN  ...                0.0              0.0

[20000 rows x 13 columns]>

In [17]:
## Divide the dataset into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

## Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
X_train

array([[-0.70157205,  0.90488898,  0.00509723, ...,         nan,
                nan,         nan],
       [ 0.25470059,  0.90488898,  2.57743383, ...,         nan,
                nan,         nan],
       [-0.80551473,  0.90488898,  1.24362967, ...,         nan,
                nan,         nan],
       ...,
       [ 0.87835666, -1.10510794, -0.09017449, ...,         nan,
                nan,         nan],
       [ 0.17154644,  0.90488898,  0.38618414, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,  0.99167946,
        -0.5804702 , -0.5677979 ]])

In [27]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### Now will train ANN

### In basic ANN we have 1 input layer, few hidden layers and one output layer

### Then we perform forward propogation and backward propogation

### In Tensorflow we call ANN as sequential model
### When we start creating our ANN model

### 1. We need to initialize our sequential network
### 2. Then we need to create a hidden neuron, so we need to use 'Dense' library from keras
### 3. Activation function to be applied to every node -> Sigmoid, tab h ,Relu, Leaky Relu etc any can be applied
### 4. Optimizer - useful in back propogation - responsible in updating the weights
### 5. Loss function, try to reduce this
### 6. Metrics - usually in classification problem metrics is 'accuracy', in regression problem it is like mse, or mean absolute error etc
### 7. Training information - store logs in a folder and we use tensorboard which will display these logs in a vizualization graphs so easy to understand

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [21]:
(X_train.shape[1],)

(12,)

In [22]:
## Lets build our ANN model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## 1st hidden layer and connected with input layer
    Dense(32,activation='relu'), ## Hidden layer 2
    Dense(1,activation='sigmoid') ## output layer
])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [50]:
## optimizers
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [51]:
## Now our ANN model is ready as we saw above
## In order to apply fwd and backward propogation we need to compile this model
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [58]:
## Set up the tensorboard
import datetime
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir,histogram_freq=1)

In [59]:
## Setup Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [60]:
## Now, Time to Train the Model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test), epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
500/500 [==============================] - 0s 675us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 2/100
500/500 [==============================] - 0s 654us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 3/100
500/500 [==============================] - 0s 588us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 4/100
500/500 [==============================] - 0s 693us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 5/100
500/500 [==============================] - 0s 617us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 6/100
500/500 [==============================] - 0s 614us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 7/100
500/500 [==============================] - 0s 605us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 8/100
500/500 [==============================] - 0s 601us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 9/100
500/500 [==============================] - 0s 586us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045
Epoch 10/100
500/500 [==============================] - 0s 590us/step - loss: nan - accuracy: 0.3966 - val_loss: nan - val_accuracy: 0.4045

In [61]:
model.save('model.h5')

/Users/harshveersinghnirwan/Downloads/annclassification_myproject/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [72]:
## Lets load tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [84]:
## to kill and restart the tensorboard
!kill 81700

In [73]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 81700), started 21:20:15 ago. (Use '!kill 81700' to kill it.)

In [74]:
import numpy as np

# Check for Not-a-Number (NaN)
print("X_train has NaNs:", np.any(np.isnan(X_train)))
print("y_train has NaNs:", np.any(np.isnan(y_train)))

# Check for Infinite (Inf) values (can be caused by division by zero)
print("X_train has Inf:", np.any(np.isinf(X_train)))
print("y_train has Inf:", np.any(np.isinf(y_train)))

X_train has NaNs: True
y_train has NaNs: True
X_train has Inf: False
y_train has Inf: False

In [75]:
# 1. Combine the NaN check for X_train and y_train
# np.any(np.isnan(X_train), axis=1) finds rows in X that have NaNs
# np.isnan(y_train) finds elements in y that are NaNs (assuming y is 1D)

# Create a boolean mask: True for rows we need to REMOVE (the corrupted ones)
nan_mask_X = np.any(np.isnan(X_train), axis=1) # Check across all columns (axis=1)
nan_mask_y = np.isnan(y_train)

# Combine the masks to find rows that are bad in EITHER X or Y
# The ' | ' operator is the logical OR for NumPy arrays
corrupted_rows = nan_mask_X | nan_mask_y

# 2. Create the CLEAN data arrays (using the inverse of the mask)
X_train_clean = X_train[~corrupted_rows] # The '~' is the logical NOT operator
y_train_clean = y_train[~corrupted_rows]

# Report the cleanup
print(f"Original size of X_train: {len(X_train)}")
print(f"Number of corrupted rows removed: {np.sum(corrupted_rows)}")
print(f"New size of X_train_clean: {len(X_train_clean)}")

# Sanity check: Should all be False now
print("\nCheck on Clean Data:")
print("X_train_clean has NaNs:", np.any(np.isnan(X_train_clean)))
print("y_train_clean has NaNs:", np.any(np.isnan(y_train_clean)))

Original size of X_train: 16000
Number of corrupted rows removed: 16000
New size of X_train_clean: 0

Check on Clean Data:
X_train_clean has NaNs: False
y_train_clean has NaNs: False

In [76]:
# 1. Print the shape and data type (dtype)
print(f"X_train shape: {X_train.shape}")
print(f"X_train dtype: {X_train.dtype}")

# 2. Print the first 5 rows to see what the values look like
print("\nFirst 5 rows of X_train (look for NaN):")
print(X_train[:5])

# 3. Print the first 5 rows of y_train
print("\nFirst 5 rows of y_train (look for NaN):")
print(y_train[:5])

X_train shape: (16000, 12)
X_train dtype: float64

First 5 rows of X_train (look for NaN):
[[-7.01572053e-01  9.04888980e-01  5.09723429e-03 -1.38191778e+00
   8.50420026e-01  8.12004166e-01  6.49911226e-01 -1.02834286e+00
  -4.79758808e-01             nan             nan             nan]
 [ 2.54700587e-01  9.04888980e-01  2.57743383e+00  2.47181452e-03
   6.31211519e-01  8.12004166e-01  6.49911226e-01  9.72438314e-01
   5.44872204e-01             nan             nan             nan]
 [-8.05514732e-01  9.04888980e-01  1.24362967e+00  1.04076401e+00
  -1.22681683e+00  8.12004166e-01 -1.53867168e+00  9.72438314e-01
   1.35008697e+00             nan             nan             nan]
 [-2.55175173e+00  9.04888980e-01  5.09723429e-03  1.73295881e+00
  -1.22681683e+00 -9.11561060e-01  6.49911226e-01 -1.02834286e+00
   1.04688905e+00             nan             nan             nan]
 [ 1.06545348e+00 -1.10510794e+00 -7.57076571e-01  3.48569213e-01
   4.85688780e-01 -9.11561060e-01 -1.53867168e+00 -1.02834286e+00
  -1.62983806e-01             nan             nan             nan]]

First 5 rows of y_train (look for NaN):
5894    0.0
3728    0.0
8958    0.0
7671    1.0
5999    0.0
Name: Exited, dtype: float64

In [77]:
# Assuming X_train has 12 columns (0 to 11)
# You want to keep columns 0 through 8 and drop columns 9, 10, 11 (the NaNs)

# NOTE: Python uses 0-based indexing. Columns 10, 11, and 12 from your text are
#       actually indices 9, 10, and 11 in the array.

X_train_clean = X_train[:, :9]  # Keep columns from index 0 up to (but not including) 9
X_test_clean = X_test[:, :9]    # You must do the same for the test set!

# Sanity Check
print(f"New X_train shape: {X_train_clean.shape}") # Should be (16000, 9)
print(f"X_train_clean has NaNs: {np.any(np.isnan(X_train_clean))}")

# Final Clean Y (just in case)
y_train_clean = y_train.to_numpy() # Convert y to clean numpy array if it was pandas Series

New X_train shape: (16000, 9)
X_train_clean has NaNs: True

In [78]:
# Assuming X_train_clean is the (16000, 9) array you just created
import numpy as np

# 1. Calculate the mean of each column, ignoring existing NaNs
# axis=0 means calculate mean down the rows (i.e., for each column)
# keepdims=True makes the result shape compatible for broadcasting
column_means = np.nanmean(X_train_clean, axis=0, keepdims=True)

# 2. Iterate through columns and fill NaNs
for i in range(X_train_clean.shape[1]):
    # Get the mean for the current column
    mean_value = column_means[0, i]
    
    # Find all NaN indices in the current column
    nan_indices = np.isnan(X_train_clean[:, i])
    
    # Fill the NaNs with the calculated mean
    X_train_clean[nan_indices, i] = mean_value

# Sanity Check 1: Should now be False
print("X_train_clean after imputation has NaNs:", np.any(np.isnan(X_train_clean)))

# You MUST also clean y_train (which previously showed NaNs: True)
# We will drop rows in y_train corresponding to any NaNs found in X_test, 
# but for now, let's just make sure y_train is a clean NumPy array:
y_train_clean = y_train.to_numpy() # Converts pandas Series/DataFrame to numpy array

# Sanity Check 2: Final NaN check before scaling
print("y_train_clean has NaNs:", np.any(np.isnan(y_train_clean)))

X_train_clean after imputation has NaNs: False
y_train_clean has NaNs: True

In [79]:
# You must first clean X_test by slicing off the same last 3 columns (indices 9, 10, 11)
X_test_clean = X_test[:, :9]

# Use the column_means calculated from X_train_clean in Step 1
for i in range(X_test_clean.shape[1]):
    mean_value = column_means[0, i] # Use mean from TRAIN data
    nan_indices = np.isnan(X_test_clean[:, i])
    X_test_clean[nan_indices, i] = mean_value
    
print("X_test_clean after imputation has NaNs:", np.any(np.isnan(X_test_clean)))

X_test_clean after imputation has NaNs: False

In [80]:
X_train_scaled = scaler.fit_transform(X_train_clean)
X_test_scaled = scaler.transform(X_test_clean)

In [81]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [82]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 81700), started 21:33:03 ago. (Use '!kill 81700' to kill it.)

In [94]:
# Assuming 'scaler' is still defined (e.g., StandardScaler)

# 1. FIT and TRANSFORM on the CLEAN training data
X_train_scaled = scaler.fit_transform(X_train_clean)

# 2. TRANSFORM the CLEAN test data (using parameters learned from training)
X_test_scaled = scaler.transform(X_test_clean)

print("Scaling complete. Data is ready for training.")

Scaling complete. Data is ready for training.

In [105]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import regularizers

# Rebuild the model (final time)
model = Sequential([
    # Add L2 Regularization to the first layer to prevent exploding weights
    Dense(64, activation='relu', input_shape=(9,), 
          kernel_regularizer=regularizers.l2(0.01)), # CRUCIAL STABILITY CHANGE
    
    Dense(32, activation='relu'),
    
    # Keep the linear output for the stable logits loss
    Dense(1) 
])

# Recompile the model (Legacy Adam, low learning rate, logits=True)
import tensorflow as tf
from tensorflow.keras.optimizers import legacy
optimizer = legacy.Adam(learning_rate=0.00001) 
model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), 
    metrics=['accuracy']
)

In [106]:
import datetime
from tensorflow.keras.callbacks import TensorBoard

# Create a new, unique log directory path
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1) 

# Assuming early_stopping_callback is still defined

In [107]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Final rebuild with input_shape=(9,)
model = Sequential([
    # Input layer: 9 features
    Dense(64, activation='relu', input_shape=(9,)), 
    
    # Hidden layers
    Dense(32, activation='relu'),
    
    # Output layer: USE LINEAR ACTIVATION (or just omit 'activation')
    Dense(1) # Defaults to linear activation (i.e., logits)
])

In [108]:
import numpy as np
# The shape should be 1D, and the dtype should be integer or float
print(f"y_train_clean shape: {y_train_clean.shape}")
print(f"y_train_clean dtype: {y_train_clean.dtype}")

# Check for Non-Binary values (must be 0 or 1)
unique_labels = np.unique(y_train_clean)
print(f"y_train_clean unique values: {unique_labels}")

# Final NaN/Inf Check (MUST be False)
print("y_train_clean has NaNs:", np.any(np.isnan(y_train_clean)))
print("y_train_clean has Inf:", np.any(np.isinf(y_train_clean)))

y_train_clean shape: (16000,)
y_train_clean dtype: float64
y_train_clean unique values: [ 0.  1. nan]
y_train_clean has NaNs: True
y_train_clean has Inf: False

In [109]:
import numpy as np

# 1. Create a mask to identify the NaN values in the y_train_clean array
# This mask will be True for rows with NaN (the bad rows)
nan_mask_y = np.isnan(y_train_clean)

# 2. Find the inverse mask (the rows we want to KEEP)
clean_rows_mask = ~nan_mask_y

# 3. Apply the mask to both the scaled X data and the y data
X_train_final_scaled = X_train_scaled[clean_rows_mask]
y_train_final = y_train_clean[clean_rows_mask]

# Report the cleanup
print(f"Original size: {len(y_train_clean)}")
print(f"Number of NaN Y-rows removed: {np.sum(nan_mask_y)}")
print(f"Final training size: {len(y_train_final)}")

# Sanity Check: Should be False
print("\nFinal Sanity Check:")
print("y_train_final has NaNs:", np.any(np.isnan(y_train_final)))

Original size: 16000
Number of NaN Y-rows removed: 8019
Final training size: 7981

Final Sanity Check:
y_train_final has NaNs: False

In [110]:
from tensorflow.keras.optimizers import legacy
import tensorflow as tf
optimizer = legacy.Adam(learning_rate=0.00001) 
# Compile model again just to be 100% sure
model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), 
    metrics=['accuracy']
)

In [112]:
import numpy as np

# 1. Check for NaNs/Infs in the scaled test features
print("X_test_scaled has NaNs:", np.any(np.isnan(X_test_scaled)))
print("X_test_scaled has Inf:", np.any(np.isinf(X_test_scaled)))

# If either is True, you must re-run the imputation for X_test_clean
# and then re-run the scaling to get X_test_scaled.
# If they are False, the problem is in y_test.

X_test_scaled has NaNs: False
X_test_scaled has Inf: False

In [113]:
import numpy as np

# 1. Check if y_test is a Pandas Series/DataFrame (most likely) and convert to NumPy array
# If y_test is already NumPy, this does nothing harmful.
y_test_np = y_test.to_numpy() if hasattr(y_test, 'to_numpy') else y_test

# 2. Create a mask to identify the NaN values in the y_test labels
nan_mask_test_y = np.isnan(y_test_np)

# 3. Find the inverse mask (the rows we want to KEEP)
clean_test_mask = ~nan_mask_test_y

# 4. Apply the mask to both the scaled X_test data and the y_test data
X_test_final_scaled = X_test_scaled[clean_test_mask]
y_test_final = y_test_np[clean_test_mask] # Use the NumPy version

# Report the cleanup
print(f"Original y_test size: {len(y_test)}")
print(f"Number of NaN Y-test rows removed: {np.sum(nan_mask_test_y)}")
print(f"Final validation size: {len(y_test_final)}")

# Final Sanity Check
print("\nFinal Validation Sanity Check:")
print("y_test_final has NaNs:", np.any(np.isnan(y_test_final)))

Original y_test size: 4000
Number of NaN Y-test rows removed: 1981
Final validation size: 2019

Final Validation Sanity Check:
y_test_final has NaNs: False

In [116]:
# Ensure a fresh log for TensorBoard
import datetime
from tensorflow.keras.callbacks import TensorBoard
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1) 

# Assuming early_stopping_callback is defined
history = model.fit(
    X_train_final_scaled, # The final 7981 rows of scaled features
    y_train_final,        # The final 7981 rows of clean labels
    validation_data=(X_test_scaled, y_test), 
    epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 879us/step - loss: 0.5646 - accuracy: 0.7951 - val_loss: nan - val_accuracy: 0.4045
Epoch 2/100
250/250 [==============================] - 0s 734us/step - loss: 0.5449 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 3/100
250/250 [==============================] - 0s 745us/step - loss: 0.5307 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 4/100
250/250 [==============================] - 0s 728us/step - loss: 0.5196 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5107 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 6/100
250/250 [==============================] - 0s 728us/step - loss: 0.5032 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 7/100
250/250 [==============================] - 0s 770us/step - loss: 0.4967 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 8/100
250/250 [==============================] - 0s 739us/step - loss: 0.4910 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 9/100
250/250 [==============================] - 0s 736us/step - loss: 0.4860 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045
Epoch 10/100
250/250 [==============================] - 0s 741us/step - loss: 0.4814 - accuracy: 0.7950 - val_loss: nan - val_accuracy: 0.4045

In [117]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 99110), started 0:02:06 ago. (Use '!kill 99110' to kill it.)